/**
 * Cloud Functions Index for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 */

const admin = require('firebase-admin');
const functions = require('firebase-functions');

// Initialize Firebase Admin
admin.initializeApp();

// Import handlers
const { processJob } = require('./jobProcessor');
const { createTestJob } = require('./testJob');

// Job processor (Firestore trigger)
exports.processJob = functions.firestore
  .document('jobs/{jobId}')
  .onCreate(processJob);

// Test job creation endpoint (HTTP)
exports.createTestJob = functions.https.onRequest(createTestJob);

console.log('[V3 Functions] Cloud Functions initialized');
