/**
 * Job Processor for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 */

const admin = require('firebase-admin');
const GeminiClient = require('./gemini');

async function processJob(snap, context) {
  const jobId = context.params.jobId;
  const job = snap.data();

  console.log(`[JobProcessor] Processing job ${jobId}`);

  const db = admin.firestore();
  const jobRef = db.collection('jobs').doc(jobId);

  try {
    await jobRef.update({
      status: 'processing',
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    const apiKey = process.env.GEMINI_API_KEY;
    const gemini = new GeminiClient(apiKey);

    const startTime = Date.now();
    let result;

    if (job.type === 'image') {
      result = await gemini.generateImage(job.prompt, job.format || '1:1');
    } else {
      result = await gemini.generateVideo(job.prompt, job.format || '16:9');
    }

    const processingTimeMs = Date.now() - startTime;

    // Phase 1: Use the placeholder URL directly from Gemini
    // Phase 2: Download the actual image/video and upload to our storage
    await jobRef.update({
      status: 'complete',
      result: { url: result.url, metadata: result.metadata },
      processedAt: admin.firestore.FieldValue.serverTimestamp(),
      processingTimeMs,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    console.log(`[JobProcessor] Job ${jobId} completed`);

  } catch (error) {
    console.error(`[JobProcessor] Job ${jobId} failed:`, error);
    await jobRef.update({
      status: 'error',
      error: error.message,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });
    throw error;
  }
}

async function uploadToStorage(jobId, type, result) {
  const bucket = admin.storage().bucket();
  const folder = type === 'image' ? 'images' : 'videos';
  const ext = type === 'image' ? 'png' : 'mp4';
  const fileName = `${folder}/${jobId}.${ext}`;

  const file = bucket.file(fileName);
  const placeholder = JSON.stringify({ jobId, type, metadata: result.metadata });

  await file.save(placeholder, {
    metadata: { contentType: result.metadata.mimeType },
    public: true
  });

  return `https://storage.googleapis.com/${bucket.name}/${fileName}`;
}

module.exports = { processJob };
