/**
 * Test Job Endpoint for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 */

const admin = require('firebase-admin');

async function createTestJob(req, res) {
  // Enable CORS
  res.set('Access-Control-Allow-Origin', '*');
  res.set('Access-Control-Allow-Methods', 'GET, POST');
  res.set('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight request
  if (req.method === 'OPTIONS') {
    res.status(204).send('');
    return;
  }

  try {
    const { type = 'image', prompt, format } = req.body;

    const db = admin.firestore();
    const jobRef = await db.collection('jobs').add({
      status: 'pending',
      type: type,
      prompt: prompt || `Test ${type} generation`,
      format: format || (type === 'image' ? '1:1' : '16:9'),
      context: { source: 'test-endpoint' },
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    console.log(`[TestJob] Created test job: ${jobRef.id}`);

    res.json({
      success: true,
      jobId: jobRef.id,
      message: `Test ${type} job created`
    });

  } catch (error) {
    console.error('[TestJob] Error:', error);
    res.status(500).json({ success: false, error: error.message });
  }
}

module.exports = { createTestJob };
